# permissions for end users to edit clustermanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustermanager-editor-role
rules:
- apiGroups:
  - cluster.tmax.io
  resources:
  - clustermanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.tmax.io
  resources:
  - clustermanagers/status
  verbs:
  - get
