# permissions for end users to view clustermanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustermanager-viewer-role
rules:
- apiGroups:
  - cluster.tmax.io
  resources:
  - clustermanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.tmax.io
  resources:
  - clustermanagers/status
  verbs:
  - get
